export const RPC_INVALID_PARAMS_ERR_CODE = -32021;
export const RPC_USER_ALREADY_EXISTS_ERR_CODE = -32001;
export const RPC_INVALID_CREDENTIALS_ERR_CODE = -32002;
export const RPC_RESOURCE_NOT_FOUND_ERR_CODE = -32022;
export const RPC_INSUFFICIENT_BALANCE_ERR_CODE = -32008;
export const RPC_NOT_PURCHASED_ERR_CODE = -31006;
